[package]
name = "ijiege-os"
version = "0.1.0"
edition = "2021"
authors = ["智能杰哥"]

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
smoltcp = { version = "0.13", default-features = false, features = [
    "proto-ipv4", "proto-tcp", "proto-udp",
    "socket-tcp", "socket-udp",
    "medium-ethernet",
    "alloc",
] }


[profile.release]
opt-level = 3
debug = true
lto = false
