[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
path = "src/main.rs"

[profile.release]
panic = "abort"
opt-level = 2
debug = true
lto = false

[profile.dev]
panic = "abort"

[dependencies]
riscv = "0.11"
sbi-rt = { version = "0.0.3", features = ["legacy"] }
buddy_system_allocator = "0.10"
bitflags = "2"
xmas-elf = { version = "0.9", default-features = false }
virtio-drivers = "0.7"
smoltcp = { version = "0.11", default-features = false, features = ["alloc", "medium-ethernet", "proto-ipv4", "socket-tcp", "socket-udp", "proto-dhcpv4", "socket-dhcpv4"] }
spin = "0.9"
log = "0.4"
