daemon off;
master_process off;
worker_processes 1;
error_log /dev/stderr info;
pid /nginx/logs/nginx.pid;

events {
    worker_connections 128;
    use poll;
}

http {
    access_log off;
    sendfile off;
    default_type application/octet-stream;
    types {
        text/html                             html htm;
        text/css                              css;
        text/plain                            txt;
        application/javascript                js;
        image/png                             png;
        image/jpeg                            jpg jpeg;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            root /nginx/html;
            index index.html;
        }
    }
}
