user root;
worker_processes 1;
daemon off;
master_process off;
error_log /dev/stderr info;
pid /run/nginx.pid;

events {
    worker_connections 32;
    use epoll;
}

http {
    access_log off;
    sendfile off;
    default_type text/plain;
    keepalive_timeout 5;
    server {
        listen 80;
        server_name _;
        location / {
            root /var/www;
            index index.html;
        }
    }
}

