error_log /dev/stderr notice;
worker_processes 1;
daemon off;
master_process off;

events {
    worker_connections 32;
}

http {
    access_log off;
    server {
        listen 80;
        root /var/www;
    }
}
