daemon off;
master_process off;
worker_processes 1;
error_log stderr notice;
pid /nginx.pid;

events {
    worker_connections 64;
}

http {
    include /etc/nginx/mime.types;
    access_log off;
    server {
        listen 80;
        server_name _;
        root /var/lib/nginx/html;
        location / { index index.html; }
    }
}
