//! Linux riscv64 syscall numbers (the generic asm-generic/unistd.h table).

pub const GETCWD: usize = 17;
pub const EVENTFD2: usize = 19;
pub const EPOLL_CREATE1: usize = 20;
pub const EPOLL_CTL: usize = 21;
pub const EPOLL_PWAIT: usize = 22;
pub const DUP: usize = 23;
pub const DUP3: usize = 24;
pub const FCNTL: usize = 25;
pub const INOTIFY_INIT1: usize = 26;
pub const IOCTL: usize = 29;
pub const MKNODAT: usize = 33;
pub const MKDIRAT: usize = 34;
pub const UNLINKAT: usize = 35;
pub const SYMLINKAT: usize = 36;
pub const LINKAT: usize = 37;
pub const RENAMEAT: usize = 38;
pub const UMOUNT2: usize = 39;
pub const MOUNT: usize = 40;
pub const STATFS: usize = 43;
pub const FSTATFS: usize = 44;
pub const TRUNCATE: usize = 45;
pub const FTRUNCATE: usize = 46;
pub const FACCESSAT: usize = 48;
pub const CHDIR: usize = 49;
pub const FCHDIR: usize = 50;
pub const CHROOT: usize = 51;
pub const FCHMOD: usize = 52;
pub const FCHMODAT: usize = 53;
pub const FCHOWNAT: usize = 54;
pub const FCHOWN: usize = 55;
pub const OPENAT: usize = 56;
pub const CLOSE: usize = 57;
pub const PIPE2: usize = 59;
pub const GETDENTS64: usize = 61;
pub const LSEEK: usize = 62;
pub const READ: usize = 63;
pub const WRITE: usize = 64;
pub const READV: usize = 65;
pub const WRITEV: usize = 66;
pub const PREAD64: usize = 67;
pub const PWRITE64: usize = 68;
pub const SENDFILE: usize = 71;
pub const PSELECT6: usize = 72;
pub const PPOLL: usize = 73;
pub const READLINKAT: usize = 78;
pub const FSTATAT: usize = 79;
pub const FSTAT: usize = 80;
pub const SYNC: usize = 81;
pub const FSYNC: usize = 82;
pub const FDATASYNC: usize = 83;
pub const UTIMENSAT: usize = 88;
pub const EXIT: usize = 93;
pub const EXIT_GROUP: usize = 94;
pub const SET_TID_ADDRESS: usize = 96;
pub const UNSHARE: usize = 97;
pub const FUTEX: usize = 98;
pub const SET_ROBUST_LIST: usize = 99;
pub const GET_ROBUST_LIST: usize = 100;
pub const NANOSLEEP: usize = 101;
pub const GETITIMER: usize = 102;
pub const SETITIMER: usize = 103;
pub const CLOCK_GETTIME: usize = 113;
pub const CLOCK_SETTIME: usize = 112;
pub const CLOCK_GETRES: usize = 114;
pub const CLOCK_NANOSLEEP: usize = 115;
pub const SCHED_SETAFFINITY: usize = 122;
pub const SCHED_GETAFFINITY: usize = 123;
pub const SCHED_YIELD: usize = 124;
pub const SCHED_GETPARAM: usize = 121;
pub const SCHED_SETSCHEDULER: usize = 119;
pub const SCHED_GETSCHEDULER: usize = 120;
pub const SCHED_GET_PRIORITY_MAX: usize = 125;
pub const SCHED_GET_PRIORITY_MIN: usize = 126;
pub const KILL: usize = 129;
pub const TKILL: usize = 130;
pub const TGKILL: usize = 131;
pub const SIGALTSTACK: usize = 132;
pub const RT_SIGSUSPEND: usize = 133;
pub const RT_SIGACTION: usize = 134;
pub const RT_SIGPROCMASK: usize = 135;
pub const RT_SIGPENDING: usize = 136;
pub const RT_SIGTIMEDWAIT: usize = 137;
pub const RT_SIGQUEUEINFO: usize = 138;
pub const RT_SIGRETURN: usize = 139;
pub const SETPRIORITY: usize = 140;
pub const GETPRIORITY: usize = 141;
pub const SETREGID: usize = 143;
pub const SETGID: usize = 144;
pub const SETREUID: usize = 145;
pub const SETUID: usize = 146;
pub const SETRESUID: usize = 147;
pub const GETRESUID: usize = 148;
pub const SETRESGID: usize = 149;
pub const GETRESGID: usize = 150;
pub const SETFSUID: usize = 151;
pub const SETFSGID: usize = 152;
pub const TIMES: usize = 153;
pub const SETPGID: usize = 154;
pub const GETPGID: usize = 155;
pub const GETSID: usize = 156;
pub const SETSID: usize = 157;
pub const GETGROUPS: usize = 158;
pub const SETGROUPS: usize = 159;
pub const UNAME: usize = 160;
pub const GETRLIMIT: usize = 163;
pub const SETRLIMIT: usize = 164;
pub const GETRUSAGE: usize = 165;
pub const UMASK: usize = 166;
pub const PRCTL: usize = 167;
pub const GETTIMEOFDAY: usize = 169;
pub const SETTIMEOFDAY: usize = 170;
pub const GETPID: usize = 172;
pub const GETPPID: usize = 173;
pub const GETUID: usize = 174;
pub const GETEUID: usize = 175;
pub const GETGID: usize = 176;
pub const GETEGID: usize = 177;
pub const GETTID: usize = 178;
pub const SYSINFO: usize = 179;
pub const SHMGET: usize = 194;
pub const SHMCTL: usize = 195;
pub const SHMAT: usize = 196;
pub const SHMDT: usize = 197;
pub const SOCKET: usize = 198;
pub const SOCKETPAIR: usize = 199;
pub const BIND: usize = 200;
pub const LISTEN: usize = 201;
pub const ACCEPT: usize = 202;
pub const CONNECT: usize = 203;
pub const GETSOCKNAME: usize = 204;
pub const GETPEERNAME: usize = 205;
pub const SENDTO: usize = 206;
pub const RECVFROM: usize = 207;
pub const SETSOCKOPT: usize = 208;
pub const GETSOCKOPT: usize = 209;
pub const SHUTDOWN: usize = 210;
pub const SENDMSG: usize = 211;
pub const RECVMSG: usize = 212;
pub const READAHEAD: usize = 213;
pub const BRK: usize = 214;
pub const MUNMAP: usize = 215;
pub const MREMAP: usize = 216;
pub const CLONE: usize = 220;
pub const EXECVE: usize = 221;
pub const MMAP: usize = 222;
pub const FADVISE64: usize = 223;
pub const MPROTECT: usize = 226;
pub const MSYNC: usize = 227;
pub const MLOCK: usize = 228;
pub const MUNLOCK: usize = 229;
pub const MLOCKALL: usize = 230;
pub const MUNLOCKALL: usize = 231;
pub const MADVISE: usize = 233;
pub const WAIT4: usize = 260;
pub const PRLIMIT64: usize = 261;
pub const RENAMEAT2: usize = 276;
pub const GETRANDOM: usize = 278;
pub const MEMFD_CREATE: usize = 279;
pub const STATX: usize = 291;
pub const RSEQ: usize = 293;
pub const CLONE3: usize = 435;
pub const CLOSE_RANGE: usize = 436;
pub const FACCESSAT2: usize = 439;
pub const EPOLL_PWAIT2: usize = 441;
pub const ACCEPT4: usize = 242;
pub const EVENTFD: usize = 19;
pub const RISCV_HWPROBE: usize = 258;
pub const RISCV_FLUSH_ICACHE: usize = 259;

/// Return a name for logging.
pub fn name(n: usize) -> &'static str {
    match n {
        GETCWD => "getcwd",
        EPOLL_CREATE1 => "epoll_create1",
        EPOLL_CTL => "epoll_ctl",
        EPOLL_PWAIT => "epoll_pwait",
        EPOLL_PWAIT2 => "epoll_pwait2",
        DUP => "dup",
        DUP3 => "dup3",
        FCNTL => "fcntl",
        IOCTL => "ioctl",
        MKDIRAT => "mkdirat",
        MKNODAT => "mknodat",
        UNLINKAT => "unlinkat",
        SYMLINKAT => "symlinkat",
        LINKAT => "linkat",
        RENAMEAT => "renameat",
        RENAMEAT2 => "renameat2",
        STATFS => "statfs",
        FSTATFS => "fstatfs",
        TRUNCATE => "truncate",
        FTRUNCATE => "ftruncate",
        FACCESSAT => "faccessat",
        FACCESSAT2 => "faccessat2",
        CHDIR => "chdir",
        FCHDIR => "fchdir",
        CHROOT => "chroot",
        FCHMOD => "fchmod",
        FCHMODAT => "fchmodat",
        FCHOWNAT => "fchownat",
        FCHOWN => "fchown",
        OPENAT => "openat",
        CLOSE => "close",
        PIPE2 => "pipe2",
        GETDENTS64 => "getdents64",
        LSEEK => "lseek",
        READ => "read",
        WRITE => "write",
        READV => "readv",
        WRITEV => "writev",
        PREAD64 => "pread64",
        PWRITE64 => "pwrite64",
        SENDFILE => "sendfile",
        PSELECT6 => "pselect6",
        PPOLL => "ppoll",
        READLINKAT => "readlinkat",
        FSTATAT => "fstatat",
        FSTAT => "fstat",
        STATX => "statx",
        SYNC => "sync",
        FSYNC => "fsync",
        FDATASYNC => "fdatasync",
        UTIMENSAT => "utimensat",
        EXIT => "exit",
        EXIT_GROUP => "exit_group",
        SET_TID_ADDRESS => "set_tid_address",
        FUTEX => "futex",
        SET_ROBUST_LIST => "set_robust_list",
        GET_ROBUST_LIST => "get_robust_list",
        NANOSLEEP => "nanosleep",
        CLOCK_GETTIME => "clock_gettime",
        CLOCK_SETTIME => "clock_settime",
        CLOCK_GETRES => "clock_getres",
        CLOCK_NANOSLEEP => "clock_nanosleep",
        GETITIMER => "getitimer",
        SETITIMER => "setitimer",
        SCHED_YIELD => "sched_yield",
        SCHED_SETAFFINITY => "sched_setaffinity",
        SCHED_GETAFFINITY => "sched_getaffinity",
        SCHED_GETPARAM => "sched_getparam",
        SCHED_SETSCHEDULER => "sched_setscheduler",
        SCHED_GETSCHEDULER => "sched_getscheduler",
        KILL => "kill",
        TKILL => "tkill",
        TGKILL => "tgkill",
        SIGALTSTACK => "sigaltstack",
        RT_SIGSUSPEND => "rt_sigsuspend",
        RT_SIGACTION => "rt_sigaction",
        RT_SIGPROCMASK => "rt_sigprocmask",
        RT_SIGPENDING => "rt_sigpending",
        RT_SIGTIMEDWAIT => "rt_sigtimedwait",
        RT_SIGRETURN => "rt_sigreturn",
        SETGID => "setgid",
        SETUID => "setuid",
        SETREUID => "setreuid",
        SETREGID => "setregid",
        SETRESUID => "setresuid",
        SETRESGID => "setresgid",
        GETRESUID => "getresuid",
        GETRESGID => "getresgid",
        TIMES => "times",
        SETPGID => "setpgid",
        GETPGID => "getpgid",
        GETSID => "getsid",
        SETSID => "setsid",
        GETGROUPS => "getgroups",
        SETGROUPS => "setgroups",
        UNAME => "uname",
        GETRLIMIT => "getrlimit",
        SETRLIMIT => "setrlimit",
        PRLIMIT64 => "prlimit64",
        GETRUSAGE => "getrusage",
        UMASK => "umask",
        PRCTL => "prctl",
        GETTIMEOFDAY => "gettimeofday",
        GETPID => "getpid",
        GETPPID => "getppid",
        GETUID => "getuid",
        GETEUID => "geteuid",
        GETGID => "getgid",
        GETEGID => "getegid",
        GETTID => "gettid",
        SYSINFO => "sysinfo",
        SOCKET => "socket",
        SOCKETPAIR => "socketpair",
        BIND => "bind",
        LISTEN => "listen",
        ACCEPT => "accept",
        ACCEPT4 => "accept4",
        CONNECT => "connect",
        GETSOCKNAME => "getsockname",
        GETPEERNAME => "getpeername",
        SENDTO => "sendto",
        RECVFROM => "recvfrom",
        SETSOCKOPT => "setsockopt",
        GETSOCKOPT => "getsockopt",
        SHUTDOWN => "shutdown",
        SENDMSG => "sendmsg",
        RECVMSG => "recvmsg",
        BRK => "brk",
        MUNMAP => "munmap",
        MREMAP => "mremap",
        CLONE => "clone",
        CLONE3 => "clone3",
        EXECVE => "execve",
        MMAP => "mmap",
        MPROTECT => "mprotect",
        MSYNC => "msync",
        MADVISE => "madvise",
        MLOCK => "mlock",
        MLOCKALL => "mlockall",
        WAIT4 => "wait4",
        GETRANDOM => "getrandom",
        MEMFD_CREATE => "memfd_create",
        EVENTFD2 => "eventfd2",
        INOTIFY_INIT1 => "inotify_init1",
        CLOSE_RANGE => "close_range",
        SHMGET => "shmget",
        SHMAT => "shmat",
        SHMCTL => "shmctl",
        SHMDT => "shmdt",
        RSEQ => "rseq",
        RISCV_HWPROBE => "riscv_hwprobe",
        RISCV_FLUSH_ICACHE => "riscv_flush_icache",
        FADVISE64 => "fadvise64",
        READAHEAD => "readahead",
        UNSHARE => "unshare",
        MOUNT => "mount",
        UMOUNT2 => "umount2",
        SETPRIORITY => "setpriority",
        GETPRIORITY => "getpriority",
        _ => "unknown",
    }
}
