daemon off;
master_process off;
worker_processes 1;
pid /run/nginx.pid;
error_log stderr info;
events {
    worker_connections 128;
    use epoll;
}
http {
    access_log /dev/stdout;
    default_type text/html;
    sendfile on;
    server {
        listen 8080;
        server_name localhost;
        root /www;
        location / { index index.html; }
    }
}
