# Minimal nginx config for JiegeOS
daemon off;
master_process off;
pid /tmp/nginx.pid;
error_log /var/log/nginx/error.log info;

events {
    worker_connections 64;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /var/log/nginx/access.log;
    sendfile off;

    server {
        listen 80;
        server_name localhost;

        location / {
            root /var/www;
            index index.html;
        }
    }
}
