worker_processes 1;
master_process off;
daemon off;
error_log stderr notice;
pid /var/run/nginx.pid;

events {
    worker_connections 256;
}

http {
    default_type text/html;
    access_log /var/log/nginx/access.log;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
