worker_processes 1;
pid /run/nginx.pid;
error_log stderr;

events {
    worker_connections 8;
}

http {
    default_type text/plain;
    access_log off;

    server {
        listen 80;
        return 200 "Hello from JiegeOS\n";
    }
}
